/*
冬眠キャラのデータを登録するテーブルのアクセスポリシー
*/
/* 閲覧：公開中の投稿、またはログインユーザ自身の投稿を閲覧できる */
CREATE POLICY FREEZED_CHARA_SELECT_POLICY
ON PUBLIC.FREEZED_CHARA
FOR SELECT
TO ANON, AUTHENTICATED
USING (
    STATUS = '0'
    OR USER_ID = (SELECT AUTH.UID())
);
/* ログインユーザが自分のユーザIDで投稿できる */
CREATE POLICY FREEZED_CHARA_INSERT_POLICY
ON PUBLIC.FREEZED_CHARA
FOR INSERT
TO AUTHENTICATED
WITH CHECK (
    USER_ID = (SELECT AUTH.UID())
    AND STATUS IN ('0', '1')
);
/* 投稿者本人だけが投稿を更新できる */
CREATE POLICY FREEZED_CHARA_UPDATE_POLICY
ON PUBLIC.FREEZED_CHARA
FOR UPDATE
TO AUTHENTICATED
USING (
    USER_ID = (SELECT AUTH.UID())
)
WITH CHECK (
    USER_ID = (SELECT AUTH.UID())
    AND STATUS IN ('0', '1', '2')
);
/* 投稿者本人だけが投稿を物理削除できる */
CREATE POLICY FREEZED_CHARA_DELETE_POLICY
ON PUBLIC.FREEZED_CHARA
FOR DELETE
TO AUTHENTICATED
USING (
    USER_ID = (SELECT AUTH.UID())
);
